"""Tenant-scoped access to conversations and their message history.

Every public method takes the caller's `tenant_id` as a required argument and puts it in
the WHERE clause, the same rule as `TicketRepository`. A conversation id is generated by
the server in `create` and bound to the tenant there; from then on only that tenant can
read or extend it. A conversation of another tenant is reported exactly like a missing
one.
"""

from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.orm import Session

from ticket_agent.agent.message_serialisation import (
    message_from_role_and_content,
    role_and_content_of,
)
from ticket_agent.db.models import ConversationMessage, TenantConversation
from ticket_agent.llm.conversation import Message


class ConversationNotFound(Exception):
    """The conversation id is not visible to the caller's tenant.

    Raised identically for an id that does not exist and for one that belongs to
    another tenant, so the error cannot be used to probe other tenants' conversations.
    """

    def __init__(self, conversation_id: str) -> None:
        """Record the id that was requested."""
        super().__init__(f"conversation {conversation_id} not found")
        self.conversation_id = conversation_id


class TenantConversationStore:
    """Tenant-scoped reads and appends over the conversation tables for one session.

    Write methods commit before returning.
    """

    def __init__(self, session: Session) -> None:
        """Bind the store to `session`; the caller owns the session's lifetime."""
        self._session = session

    def get(self, tenant_id: str, conversation_id: str) -> TenantConversation:
        """Return the conversation `conversation_id` if it belongs to `tenant_id`.

        Args:
            tenant_id: the caller's tenant, taken from the request, never from a model.
            conversation_id: the id to look up, as sent in the request path.

        Returns:
            The conversation row.

        Raises:
            ConversationNotFound: the id does not exist or belongs to another tenant.
        """
        statement = (
            select(TenantConversation)
            .where(TenantConversation.tenant_id == tenant_id)
            .where(TenantConversation.id == conversation_id)
        )
        conversation = self._session.scalars(statement).first()
        is_visible_to_tenant = conversation is not None

        if not is_visible_to_tenant:
            raise ConversationNotFound(conversation_id)

        return conversation

    def create(self, tenant_id: str) -> TenantConversation:
        """Create an empty conversation owned by `tenant_id` with a fresh id and commit.

        The id is a random UUID generated here, never taken from the client, so an id
        cannot be chosen to collide with or point at another tenant's conversation.

        Args:
            tenant_id: the caller's tenant, taken from the request, never from a model.

        Returns:
            The newly created conversation row, with its id.
        """
        conversation_id = uuid4().hex
        conversation = TenantConversation(id=conversation_id, tenant_id=tenant_id)

        self._session.add(conversation)
        self._session.commit()

        return conversation

    def history(self, tenant_id: str, conversation_id: str) -> list[Message]:
        """Return every message of the conversation, oldest first.

        Args:
            tenant_id: the caller's tenant, taken from the request, never from a model.
            conversation_id: the conversation to read.

        Returns:
            The rebuilt history messages; empty for a conversation with no messages.

        Raises:
            ConversationNotFound: the id does not exist or belongs to another tenant.
        """
        conversation = self.get(tenant_id, conversation_id)

        messages = []
        for row in conversation.messages:
            message = message_from_role_and_content(row.role, row.content)
            messages.append(message)

        return messages

    def append(self, tenant_id: str, conversation_id: str, message: Message) -> None:
        """Store `message` as the newest entry of the conversation and commit.

        Args:
            tenant_id: the caller's tenant, taken from the request, never from a model.
            conversation_id: the conversation to extend.
            message: the user, assistant or tool-result message to store.

        Raises:
            ConversationNotFound: the id does not exist or belongs to another tenant.
        """
        conversation = self.get(tenant_id, conversation_id)
        role, content = role_and_content_of(message)

        row = ConversationMessage(
            tenant_conversation_id=conversation.id, role=role, content=content
        )
        self._session.add(row)
        self._session.commit()
