"""ORM models: the tenants, their tickets, and the conversations held with the agent."""

from datetime import UTC, datetime

from sqlalchemy import JSON, DateTime, ForeignKey, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from ticket_agent.constants.conversations import CONVERSATION_ID_MAX_LENGTH


def utc_now() -> datetime:
    """Return the current time as a timezone-aware UTC datetime.

    This function is purely for convenience.
    """
    now = datetime.now(UTC)

    return now


class Base(DeclarativeBase):
    """Declarative base shared by every model so one metadata describes the schema."""


class Tenant(Base):
    """One customer organisation; every ticket belongs to exactly one tenant."""

    __tablename__ = "tenants"

    # Short slug used as the value of the `X-Tenant-ID` header, e.g. `acme`.
    id: Mapped[str] = mapped_column(String(64), primary_key=True)

    # Human-readable name shown in the login screen.
    display_name: Mapped[str] = mapped_column(String(128), nullable=False)

    tickets: Mapped[list["Ticket"]] = relationship(back_populates="tenant")


class Ticket(Base):
    """One support ticket. Ids are global integers on purpose.

    A ticket id from another tenant is easy to guess (the brief's "ticket #47"), so the
    only thing that keeps it out of reach is the tenant filter every repository query
    applies. The description is free text written by end users and may contain
    prompt-injection payloads; it is data, never an instruction.
    """

    __tablename__ = "tickets"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    tenant_id: Mapped[str] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )

    title: Mapped[str] = mapped_column(String(200), nullable=False)

    description: Mapped[str] = mapped_column(Text, nullable=False)

    # One of `constants.tickets.TICKET_STATUSES`.
    status: Mapped[str] = mapped_column(String(32), nullable=False)

    # One of `constants.tickets.TICKET_PRIORITIES`.
    priority: Mapped[str] = mapped_column(String(32), nullable=False)

    # E-mail address of the person who opened the ticket, as they typed it.
    requester_email: Mapped[str] = mapped_column(String(254), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now
    )

    tenant: Mapped[Tenant] = relationship(back_populates="tickets")


class TenantConversation(Base):
    """One chat between a tenant's user and the agent, with its messages in order.

    The id is generated by the server when the row is created and bound to the tenant
    there. Every lookup takes the tenant id as well, so a conversation of another tenant
    is unreachable even when its id is known.
    """

    __tablename__ = "tenant_conversations"

    id: Mapped[str] = mapped_column(String(CONVERSATION_ID_MAX_LENGTH), primary_key=True)

    tenant_id: Mapped[str] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )

    messages: Mapped[list["ConversationMessage"]] = relationship(
        back_populates="conversation",
        order_by="ConversationMessage.id",
        cascade="all, delete-orphan",
    )


class ConversationMessage(Base):
    """One stored message of a conversation: who produced it and its content as JSON.

    The content holds the fields of the provider-neutral message it was made from (see
    `agent.message_serialisation`), including the opaque provider state that must be
    resent unchanged with the history.
    """

    __tablename__ = "conversation_messages"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    tenant_conversation_id: Mapped[str] = mapped_column(
        ForeignKey("tenant_conversations.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # One of `constants.conversations.MESSAGE_ROLE_*`.
    role: Mapped[str] = mapped_column(String(16), nullable=False)

    content: Mapped[dict] = mapped_column(JSON, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )

    conversation: Mapped[TenantConversation] = relationship(back_populates="messages")
